[tool.poetry]
name = "llm-experimentation"
version = "0.1.0"
description = "A repository containing research and experimentations with LLMs"
authors = ["Simone Porreca <porrecasimone@gmail.com>", "Ali Abbas Jaffri <megahertz888@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.10"
tiktoken = "^0.3.3"


[tool.poetry.group.dev.dependencies]
pandas = "^2.0.0"
numpy = "^1.24.2"
matplotlib = "^3.7.1"
jupyterlab = "^3.6.3"
openai = "^0.27.8"
langchain = "^0.0.228"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
