[tool.poetry]
name = "llm-experimentation"
version = "0.1.1"
description = "A repository containing research and experimentations with LLMs"
authors = ["Simone Porreca <porrecasimone@gmail.com>", "Ali Abbas Jaffri <megahertz888@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.10"
tiktoken = "^0.3.3"
torch = "^2.0.0"
torchvision = "^0.15.1"
pylint = "^3.0.3"
pandas = "^2.2.0"
numpy = "^1.26.4"
matplotlib = "^3.8.2"
jupyterlab = "^4.1.0"
openai = "^1.11.1"
langchain = "^0.1.5"
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
