# Project name
site_name: NexusLLM

# Define Navigation
nav:
  - NexusLLM: index.md
  - Transformers: transformers.md
  - Tokenizer: tokenizers.md
  - Embeddings: embeddings.md
  - Vector Search: vector_search.md
  - LLMs: LLMs.md
  - Google LLMs: google_llms.md
  - Fine-Tuning: fine_tuning.md
  - LLMs Evaluation: evaluation.md
  - DeepEval: deepeval.md
  - LLMOps: LLMOps.md
  - Agents: agents.md

# Theme
theme: readthedocs

# Configurations
repo_url: https://github.com/Volscente/NexusLLM
