# Workflow for deploying Mkdocs to GitHub Pages
name: Deploy MkDocs to GitHub Pages
run-name: ${{ github.actor }} Deploy Docs Workflow 📘
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # You can change this if needed

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force