# Workflow triggered on PRs that run PyLint and PyTest
name: Pull Request Workflow
run-name: ${{ github.actor }} Pull Request Workflow 🚀
on:
  pull_request:
    branches:
      - main
      - dev
env:
  DRUIDIC_GROVE_AI_ROOT_PATH: './'


jobs:
    pr_workflow:
      name: pr_workflow
      runs-on: ubuntu-latest
      steps:
        - run: echo "Running ${{ github.job }} in branch ${{ github.ref_name }}"

        # Checkout repo
        - name: Checkout
          uses: actions/checkout@v4

        # Install uv
        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v6
          with:
            version: "latest"

        # Install Python
        - name: "Set up Python"
          uses: actions/setup-python@v5
          with:
            python-version-file: ".python-version"

        # Install dependencies
        - name: Install the project
          run: uv sync --all-extras --dev

        # Lint python files
        - name: Ruff lint
          run: uv run ruff check --fix

        # Format files
        - name: Ruff format
          run: uv run ruff format

        # Unit tests
        - name: Run Unit Tests with PyTest
          run: uv run pytest